### ISSUE TITLE
Add task list formatting

### ISSUE THREAD

**Issue by zim0369** [remarkjs/remark#999]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Task list is incorrectly formatted. Remark-ls escapes brackets.

### Solution

There's no need to escape brackets. Just format task list like prettier does.

### Alternatives

-

**Comment by wooorm** [comment]
Not enough info.

**Comment by zim0369** [comment]
@wooorm 
The task list should look like this:
```md
- [ ] Artificial Intelligence
  - [ ] Unit III **Adversarial Search and Games**
  - [ ] Unit IV **Knowledge**
  - [ ] Unit V **Reasoning**
  - [ ] Unit VI **Planning**
  - [ ] Prelim Questions
```
but on saving the file it looks like:
```md
*   \[ ] Artificial Intelligence
    *   \[ ] Unit III **Adversarial Search and Games**
    *   \[ ] Unit IV **Knowledge**
    *   \[ ] Unit V **Reasoning**
    *   \[ ] Unit VI **Planning**
    *   \[ ] Prelim Questions
```
